# Generated by Django 4.1.7 on 2023-02-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('water', models.CharField(choices=[('Succulents_and_cacti', 'Succulents and cacti'), ('Drought_tolerant_plants', 'Drought-tolerant plants'), ('Moisture_loving_plants', 'Moisture-loving plants')], max_length=200)),
                ('sun', models.CharField(choices=[('Full_sun_plants', 'Full sun plants'), ('Partial_sun_partial_shade_plants', 'Partial sun/partial shade plants'), ('Shade_loving_plants', 'Shade-loving plants')], max_length=200)),
                ('soil', models.CharField(choices=[('Neutral_soil_plants', 'Neutral soil plants'), ('Alkaline_soil_plants', 'Alkaline soil plants'), ('Acidic_soil_plants', 'Acidic soil plants')], max_length=200)),
                ('leaf_type', models.CharField(choices=[('Flat_leaves', 'Flat leaves'), ('Curly_leaves', 'Curly leaves'), ('Serrated_leaves', 'Serrated leaves'), ('Semi_circular_leaves', 'Semi-circular leaves'), ('Triangular_leaves', 'Triangular leaves'), ('Variegated_leaves', 'Variegated leaves'), ('Tree_leaves', 'Tree leaves'), ('Dark_green_leaves', 'Dark green leaves'), ('Ascending_leaves', 'Ascending leaves'), ('Circular_leaves', 'Circular leaves')], max_length=200)),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
