# Generated by Django 4.1.7 on 2023-02-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='leaf_type',
            field=models.CharField(choices=[('Flat leaves', 'Flat leaves'), ('Curly leaves', 'Curly leaves'), ('Serrated leaves', 'Serrated leaves'), ('Semi circular leaves', 'Semi-circular leaves'), ('Triangular leaves', 'Triangular leaves'), ('Variegated leaves', 'Variegated leaves'), ('Tree leaves', 'Tree leaves'), ('Dark green leaves', 'Dark green leaves'), ('Ascending leaves', 'Ascending leaves'), ('Circular leaves', 'Circular leaves')], max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='soil',
            field=models.CharField(choices=[('Neutral soil plants', 'Neutral soil plants'), ('Alkaline soil plants', 'Alkaline soil plants'), ('Acidic soil plants', 'Acidic soil plants')], max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='sun',
            field=models.CharField(choices=[('Full sun plants', 'Full sun plants'), ('Partial sun partial shade plants', 'Partial sun/partial shade plants'), ('Shade loving plants', 'Shade-loving plants')], max_length=200),
        ),
        migrations.AlterField(
            model_name='plants',
            name='water',
            field=models.CharField(choices=[('Succulents and cacti', 'Succulents and cacti'), ('Drought tolerant plants', 'Drought-tolerant plants'), ('Moisture loving plants', 'Moisture-loving plants')], max_length=200),
        ),
    ]
